### ISSUE TITLE
我进不了游戏

### ISSUE THREAD

**Issue by sky2053** [OcrSu/MineCraft_LCW#36]
![Snipaste_2022-07-11_12-02-48](https://user-images.githubusercontent.com/103795275/178187274-00ca2b6b-d3af-4fa9-a6c8-26537aaf6766.png)
[错误报告-2022-7-11_12.02.22.zip](https://github.com/OcrSu/MineCraft_LCW/files/9080854/-2022-7-11_12.02.22.zip)
  

游戏版本：1.16.5

**Comment by OcrSu** [comment]
1.Hwyla 这个模组我并没有加入整合包，可能是自行或者意外加入的，删除
2.你使用了java8启动游戏，请用java11启动游戏
3.分配的内存确实很少，我不确定可以正常启动。

**Comment by sky2053** [comment]
> 1.Hwyla 这个模组我并没有加入整合包，可能是自行或者意外加入的，删除 2.你使用了java8启动游戏，请用java11启动游戏 3.分配的内存确实很少，我不确定可以正常启动。

ok,我逝逝

**Comment by OcrSu** [comment]
可以正常启动了吗？

**Comment by sky2053** [comment]
> 可以正常启动了吗？

ok
谢谢
