### ISSUE TITLE
怎么自己更新伺服器

### ISSUE THREAD

**Issue by ting100703** [OcrSu/MineCraft_LCW#39]
怎么自己更新伺服器

**Comment by OcrSu** [comment]
以LCW4.5升级到4.6为例。
1.下载4.5服务端
2.下载4.6客户端
3.根据curseforge上的更新日志  替换旧mod，删除mod，新增mod。
4.用4.6客户端config文件夹里的ftbquest文件夹替换4.5服务端config中的ftbquest文件夹。
